environment:
  epsilon: 0.5
  interpolation_period: 0.1
  max_steps: 200
  lookahead_points: 5
kinematic_constraints:
  MAX_VEL: 1.0
  MAX_ACC: 2.0
  MAX_JERK: 3.0
  MAX_ANG_VEL: 1.5
  MAX_ANG_ACC: 3.0
  MAX_ANG_JERK: 5.0
reward_weights:
  w_velocity: 2.0
  w_progress: 1.0
  w_e: 1.2
  w_action_smooth: 0.5
  w_kcm_penalty: 0.8
  w_violation: 12.0
  w_survival: 0.05
ppo:
  actor_lr: 0.0003
  critic_lr: 0.001
  hidden_dim: 64
  gamma: 0.99
  lmbda: 0.95
  epochs: 2
  eps: 0.2
  batch_size: 32
training:
  num_episodes: 2
  smoothing_factor: 0.9
  save_interval: 2
  log_interval: 1
  checkpoint_interval_steps: 256
path:
  type: 'waypoints'
  waypoints:
    - [0.0, 0.0]
    - [2.0, 0.0]
    - [2.0, 2.0]
    - [0.0, 2.0]
    - [0.0, 0.0]
  closed: true
  scale: 2.0
  num_points: 50
  s_shape:
    amplitude: 1.0
    periods: 1.0
  butterfly:
    sharpness: 1.0
    center: [0.0, 0.0]
  star:
    inner_radius: 1.0
    star_points: 5
experiment:
  mode: 'train'
  baseline_type: null
  enable_kcm: true
  model_path: null
